// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm5dfWBtDYxWbXMBqGduM4alSbj_Uug8E',
    appId: '1:63062782111:web:41d381699ec6bd7e08b2aa',
    messagingSenderId: '63062782111',
    projectId: 'blog-app-flutter-ec272',
    authDomain: 'blog-app-flutter-ec272.firebaseapp.com',
    databaseURL: 'https://blog-app-flutter-ec272-default-rtdb.firebaseio.com',
    storageBucket: 'blog-app-flutter-ec272.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDskafCZz0vqcw-DMg4eWxYluVz6qfuUtQ',
    appId: '1:63062782111:android:4be5a2f147f0026508b2aa',
    messagingSenderId: '63062782111',
    projectId: 'blog-app-flutter-ec272',
    databaseURL: 'https://blog-app-flutter-ec272-default-rtdb.firebaseio.com',
    storageBucket: 'blog-app-flutter-ec272.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUfkvvYZVfJLHGfKW3Q2G5-fQzi6TSemM',
    appId: '1:63062782111:ios:137ae4fde4647f7108b2aa',
    messagingSenderId: '63062782111',
    projectId: 'blog-app-flutter-ec272',
    databaseURL: 'https://blog-app-flutter-ec272-default-rtdb.firebaseio.com',
    storageBucket: 'blog-app-flutter-ec272.appspot.com',
    iosClientId: '63062782111-vvb7fr4jvhsjkgjoqa8uhp298kg74m12.apps.googleusercontent.com',
    iosBundleId: 'com.example.wallpaperApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUfkvvYZVfJLHGfKW3Q2G5-fQzi6TSemM',
    appId: '1:63062782111:ios:137ae4fde4647f7108b2aa',
    messagingSenderId: '63062782111',
    projectId: 'blog-app-flutter-ec272',
    databaseURL: 'https://blog-app-flutter-ec272-default-rtdb.firebaseio.com',
    storageBucket: 'blog-app-flutter-ec272.appspot.com',
    iosClientId: '63062782111-vvb7fr4jvhsjkgjoqa8uhp298kg74m12.apps.googleusercontent.com',
    iosBundleId: 'com.example.wallpaperApp',
  );
}
